### ISSUE TITLE
<align> doesn't work on <BlockQuote>

### ISSUE THREAD

**Issue by thomasfarago** [FormidableLabs/spectacle#514] opened 2018-04-17 20:47 UTC
Trying to assign align="flex-start center" to a BlockQuote.

Not working. Any way to fix this?

**Comment by manjula91** [comment] 2018-05-04 20:38
Can take this up !!

**Comment by samwhale** [comment] 2018-06-12 17:30
@thomasfarago Can you share a minimal repo with the bug?

**Comment by ebrillhart** [comment] 2018-08-27 17:05
Hi @thomasfarago the `textAlign` prop seems to be working as intended when I test it out. Closing for now, but if I'm misunderstanding the issue or you're encountering another one, please feel free to open a new issue!

**Closed** 2018-08-27 17:05 UTC
Labels: Bug, Good First Bug
