### ISSUE TITLE
Issue with ComponentPlayground

### ISSUE THREAD

**Issue by arlen-yu** [FormidableLabs/spectacle#515] opened 2018-04-19 03:30 UTC
I did a fresh clone of the boilerplate (alternatively using the `create-react-app ...` as suggested), ran `npm install` (and alternatively `yarn`), imported `ComponentPlayground`, added `<ComponentPlayground />` to an arbitrary slide, and spectacle encountered an error:

```
TypeError: Cannot read property 'buildPlaceholders' of undefined
http://localhost:3000/dist/bundle.js:58448:40
Object.run
webpack:///node_modules/prismjs/components/prism-core.js:451
highlight
webpack:///node_modules/prismjs/components/prism-core.js:280
prism
webpack:///node_modules/react-live/dist/react-live.es.js:23
```

This is on most up to date Chrome on my MBP.

**Comment by kitten** [comment] 2018-04-19 15:51
Duplicate of: https://github.com/FormidableLabs/spectacle/issues/512#issuecomment-382697952 (link leads to a proposed temporary workaround)

**Closed by kitten** 2018-04-19 15:51 UTC
