### ISSUE TITLE
Running test failed

### ISSUE THREAD

**Issue by dkosasih** [FormidableLabs/spectacle#660] opened 2019-03-11 13:35 UTC
### Question
Hi all,

I am trying to submit a PR for #657. Unfortunately, I am getting the following error when I running the test.
![image](https://user-images.githubusercontent.com/8027235/54127643-67c3a380-445e-11e9-8089-2aa0f6c9895c.png)
Does anyone have this issue before and how did you fix it?

### Background Info/Attempts
yarn version: 1.13.0
OS: Windows 10

**Comment by ebrillhart** [comment] 2019-03-27 03:20
Hi @dkosasih sorry for the delayed response! I don't off the top of my head know what the issue is here - could you open a PR using a force push or similar so that we can see your changes?

**Comment by dkosasih** [comment] 2019-03-30 03:51
I was trying to create a draft PR on #657 but I think I lost the branch completely when I switch computer before even pushing to the repo :(

let me see if I can re-create it. apologies.

**Comment by kale-stew** [comment] 2019-05-29 18:43
👋 @dkosasih - I am taking over maintenance of this repo and I want to get this feature merged in. For simplicity's sake, I'm going to close this issue and handle the failing tests in your Draft PR #664

**Closed by kale-stew** 2019-05-29 18:43 UTC
Labels: Bug, Needs Research, help wanted
