### ISSUE TITLE
Slide overwrite

### ISSUE THREAD

**Issue by dvcorreia** [FormidableLabs/spectacle#806] opened 2020-01-20 18:22 UTC
### Question

How can I prevent slide overwrite?

### Background Info/Attempts

I've separated the presentation by chapters, so I divided the slides in 2 files:

```dir
file1.js
file2.js
```

If I try to export a component with multiple slides in `file1.js` and import the component in to the main `<Deck>` they will overwrite. Example:

```js
import React, { Fragment } from 'react'
import { Slide, Heading, Text } from 'spectacle'

const Chapter1 = () => {
    return (
        <Fragment>
            <Slide>
                <Heading>Hello World 1</Heading>
            </Slide>
            <Slide>
                <Heading>Hello World 2</Heading>
            </Slide>
            <Slide>
                <Heading>Hello World 3</Heading>
            </Slide>
        </Fragment>
    )
}

export default Chapter1
```

Only the slide with the  **Hello World 3**  `<Header>` will show up in the presentation, followed by the slide in `file2.js`.

How can I prevent this from happening?

**Comment by kale-stew** [comment] 2020-01-20 20:51
Closing as duplicate of #678

**Closed by kale-stew** 2020-01-20 20:51 UTC
