### ISSUE TITLE
feature request: deep link to specific Appears

### ISSUE THREAD

**Issue by AndersDJohnson** [FormidableLabs/spectacle#396] opened 2017-11-05 20:53 UTC
Feature request to support deep-linking to specific Appear states, auto-advancing through the appears on the targeted Slide.

Something like:
* http://localhost:3000/#/4-1 or `4.1`
* http://localhost:3000/#/4-2
* etc.

Possibly also support giving `Appear`s an `id` prop, and let use refer to those in URLs as named deep-links, e.g.:

* http://localhost:3000/#/4-joke
* http://localhost:3000/#/4-punchline

Implementation could either make IDs local to each `Slide`, or global. If global, could support named global deep-links, e.g.:

* http://localhost:3000/#/joke
* http://localhost:3000/#/punchline

**Comment by kenwheeler** [comment] 2017-11-09 13:33
Closing as a dupe of #152 , definitely on deck

**Closed by kenwheeler** 2017-11-09 13:33 UTC

**Comment by AndersDJohnson** [comment] 2017-11-09 14:57
Haha, not on `<Deck>`...
