### ISSUE TITLE
`spectacle-mdx-loader`: Migration to monorepo

### ISSUE THREAD

**Issue by gksander** [FormidableLabs/spectacle#1178] opened 2022-08-01 15:39 UTC
## What?

With the migration to the spectacle monorepo, we need to also migrate the [`spectacle-mdx-loader`](https://github.com/FormidableLabs/spectacle-mdx-loader) to the monorepo. [See here](https://github.com/FormidableLabs/spectacle/wiki/Spectacle-Roadmap#spectacle-mdx-loader).

For this issue, we should create a `mdx-loader` package in the monorepo and migrate the code from the existing repository into the monorepo.

**Comment by fritz-c** [comment] 2022-09-19 15:00
Duplicate of #1164

**Closed** 2022-09-19 15:02 UTC
