### ISSUE TITLE
Presenter Mode: Notes are way too large.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/spectacle#848] opened 2020-02-24 22:25 UTC
The notes are really large, overlapping font. On Chrome, I get e.g.

![Screen Shot 2020-02-24 at 2 24 53 PM](https://user-images.githubusercontent.com/445557/75196769-7f4c7880-5711-11ea-999a-15a666ddbce4.png)

**Comment by kale-stew** [comment] 2020-03-06 01:03
I'm not able to reproduce this, @ryan-roemer - any chance you can tell me what screen size and/or zoom level you might have been using? It looks like presenter notes are at most 15px, this might have been fixed in the recent presenterMode refactor (~2 weeks ago)

**Comment by ryan-roemer** [comment] 2020-03-06 02:09
It was fixed in this PR https://github.com/FormidableLabs/spectacle/pull/850 it only manifested in MDX mode, not Jsx or md

**Closed** 2020-03-06 04:08 UTC
Labels: Bug, rewrite
