### ISSUE TITLE
Spectacle-boilerplate fails during dependency installation

### ISSUE THREAD

**Issue by Schoonology** [FormidableLabs/spectacle#315] opened 2017-05-16 21:37 UTC
OS: Mac OS v10.12.4 (Sierra)
Yarn: 0.24.4
NPM: 4.1.2
Node: 7.10.0 (tried with v7.5.0, 6.10.3, and 4.8.3)

When I try to pull spectacle-boilerplace and install dependencies, I get the following error:

```
yarn install v0.24.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-in-markdown@0.0.2" has incorrect peer dependency "markdown-to-react-components@0.2.1".
[4/4] 📃  Building fresh packages...
[1/4] ⠂ fsevents
[2/4] ⠂ radium
[3/4] ⠂ victory-core
[-/4] ⠂ waiting...
error /.../slides/node_modules/victory-core: Command failed.
Exit code: 127
Command: sh
Arguments: -c cd lib || builder run npm:postinstall
Directory: /.../slides/node_modules/victory-core
Output:
sh: line 0: cd: lib: No such file or directory
sh: builder: command not found
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by Schoonology** [comment] 2017-05-16 23:35
I'm sorry I don't know enough of this ecosystem to be more useful, but some amount of re-trying eventually passed the install step. Even though I have automated this part of the process, I have yet to find a repeatable solution.

**Comment by kenwheeler** [comment] 2017-05-17 03:19
Looking into this, thanks for the detailed report!

**Comment by ryan-roemer** [comment] 2017-05-17 04:48
I'm not able to reproduce the failure:

```sh
$ yarn install
yarn install v0.24.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-in-markdown@0.0.2" has incorrect peer dependency "markdown-to-react-components@0.2.1".
[4/4] 📃  Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "0.24.5" while you're on "0.24.4".
info To upgrade, run the following command:
$ npm upgrade --global yarn
✨  Done in 33.17s.

$ node --version && npm --version && yarn --version
v4.6.2
4.1.2
0.24.4
```

@Schoonology -- can you give us full output from a fresh `git clone` of the boilerplate on to the install?

Basically:

```sh
$ node --version && npm --version && yarn --version
$ git clone https://github.com/FormidableLabs/spectacle-boilerplate.git
$ cd spectacle-boilerplate
$ yarn install
```

Thanks!

**Comment by ryan-roemer** [comment] 2017-05-23 23:19
All victory repos now have a change merged to `master` (but not yet published) that will remove `package.json:scripts.postinstall` entirely which works around whatever the underlying behavior bug in `npm` is. (tl;dr -- this entire issue should never come up if `npm` actually worked correctly).

Watch for next version publications of `victory-core` and check to verify that https://unpkg.com/victory-core/package.json no longer contains a `postinstall`, then upgrade to that and that should completely fix this issue.

**Comment by Schoonology** [comment] 2017-05-24 15:45
This is fantastic news, @ryan-roemer, thank you!

**Closed** 2017-10-03 17:33 UTC
Labels: Needs Research
