### ISSUE TITLE
CodePane: TypeError: Cannot read property 'rest' of undefined

### ISSUE THREAD

**Issue by angelo-v** [FormidableLabs/spectacle#673] opened 2019-04-11 15:34 UTC
### Describe Your Environment

What version of Spectacle are you using? (can be found by running `npm list spectacle`)

spectacle@5.4.0 

What version of React are you using? (can be found by running `npm list react`)

16.8.4

What browser are you using?

Chrome

### Describe the Problem

**Expected behavior:** 

Using `CodePane` with `lang="json"` should render highlighted JSON code, both running the dev server and while serving the production build.

**Actual behavior:** 

Using `CodePane` with `lang="json"` fails in production build, although it works during `npm start`.

The error is:

> TypeError: Cannot read property 'rest' of undefined
    at Object.tokenize (prism-core.js:251)

### Additional Information

I did not encounter this problem with `lang="javascript"`

**Comment by barni2000** [comment] 2019-04-23 20:34
I have same issue.
javascript, clike, markup works

python, css ... is not

**Comment by barni2000** [comment] 2019-04-23 21:15
This issue is related: https://github.com/PrismJS/prism/issues/1129
Some languages is needed to be import.

**Comment by neggert** [comment] 2019-04-30 18:30
I'm seeing the same issue with python and other languages. Adding `require('prismjs/components/prism-python')` as suggested in https://github.com/PrismJS/prism/issues/1129 does not resolve the problem.

**Comment by marhaupe** [comment] 2019-05-08 16:26
I'm having the same issue. Downgrading to 5.4.0 does not solve it for me. This might help if anyone finds the time to dig into the issue: https://codesandbox.io/s/zk2p9p7jm4. In this case, the `lang` is set to `go` and produces the same issue.

**Comment by karl-run** [comment] 2019-05-26 10:59
I'm also seeing this error after upgrading from `spectacle-scripts@2.3.0` to `spectacle-scripts@2.4.0`.

I'm requiring the components, the lang argument is present, but it seems the `languages[lang]` in prism-core.js is an empty array when it attempts to tokenize.

**Comment by barni2000** [comment] 2019-06-04 09:12
@neggert The CodePane implementation should import the language specific prism module. The js module is part of the prismjs core, but python is not.

**Comment by jocaml** [comment] 2019-10-05 07:49
I spent a half hour trying to make Spectacle/Prism work with Rust syntax-coloring. Looked into code, `components/code-pane.js` uses `utils/prism-import.js` which imports `prismjs/components/prism-rust` so everything seems ok but I still get this error. Weird this hasn't been resolved yet, has anybody tried? Where should I look?

**Comment by jocaml** [comment] 2019-10-05 07:50
And what is the policy to make this bug "verified"?

**Comment by esthor** [comment] 2019-12-31 00:47
have this problem with reason language...i think it's for basically all the language besides the 4 that seem to work

**Comment by esthor** [comment] 2019-12-31 00:53
I was on latest (5.7.2)....dropping back to spectacle 5.4 solved it for me for all the highlights i need. seems after 5.4, only prism core language component bundle is being imported and the rest are being ignored. Would be great to have a fix for this! Please, someone, anyone out there?

**Comment by kale-stew** [comment] 2020-01-14 16:38
Is anyone still experiencing this issue? I've tried to reproduce in our sample presentation, internal to the repo, and in a sandbox and cannot confirm. If someone can point me to a sandbox, repo, or open a failing PR against v5.8, I can look further into it.

**Comment by kale-stew** [comment] 2020-01-20 20:54
Closing for lack of response and because I think this was fixed in our [most recent release](https://github.com/FormidableLabs/spectacle/releases/tag/v5.8.0), which updates the usage of `react-live`. Feel free to re-open this issue if the bug persists.

**Closed by kale-stew** 2020-01-20 20:54 UTC
Labels: Bug, Unverified
