### ISSUE TITLE
Issues with Prism in Vite/ESBuild-powered projects

### ISSUE THREAD

**Issue by gksander** [FormidableLabs/spectacle#1118] opened 2022-06-08 15:48 UTC
### Describe the Problem

When attempting to use Spectacle in a Vite-powered React project, the presentation fails to run with the following error:

![image](https://user-images.githubusercontent.com/12721310/172660693-4cf4d0dd-e262-482b-98e7-37ab2db35a02.png)

It appears we're running into some issues with Prism/prism-react-renderer. We should investigate and resolve this issue so that Spectacle works out of the box with Vite/other ESM-powered build tools.

**Comment by AlbertBrand** [comment] 2022-06-30 11:19
Hi, I stumbled into this problem as well trying to put Spectacle in a Vite setup.
The issue is coming from `refractor`, not `highlight.js` itself. This actually is fixed in a newer version of `refractor` so it's relatively easy to fix. If you're managing packages with `npm` v8, add the following to your `package.json`:
```
  "overrides": {
    "react-syntax-highlighter": {
      "refractor": "~3.3.1"
    }
  }
```
then do a `npm install` and the problem should be gone.

**Comment by gksander** [comment] 2022-06-30 14:54
So updating to a newer version of `react-syntax-highlighter` gets us to a sufficient version of `refractor` and seems to solve the issue. I'm noticing in a fresh Vite project, I have to update my vite config to look something like this:

```ts
export default defineConfig({
  plugins: [
    react({
      jsxRuntime: "classic",
    }),
  ],
});
```

otherwise I end up with an error like:

```text
jsx-runtime.js:6 Uncaught ReferenceError: module is not defined
    at jsx-runtime.js:6:3
```

I'm not super familiar with Vite, but I'm wondering if there's a way for us to get Spectacle working with Vite without having to configure the vite config at all.

**Closed as completed** 2022-06-30 18:36 UTC
Labels: 🐛 Bug

**Comment by gksander** [comment] 2022-06-30 19:17
This fix is now live in 9.2.1.

**Comment by AlbertBrand** [comment] 2022-07-01 07:02
@gksander Thanks for the fix. I'm not seeing the new release on npm yet, does this take some time?

**Comment by gksander** [comment] 2022-07-01 11:10
@AlbertBrand Wild. I got the email from NPM saying 9.2.1 was published, but never saw it on the registry site and figured it might just have some delay. I'm just _now_ seeing it show up. Not sure why it took so long to show up 🤷 

![image](https://user-images.githubusercontent.com/12721310/176883554-f0b19acf-636a-4c10-a295-0511c2ef1c97.png)
